# Generated by Django 5.1.1 on 2024-09-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_music_album_alter_music_band'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicartist',
            name='role',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
